struct output
{
	float4 position : POSITION;
	float2 texCoord : TEXCOORD0;
	float2 invW : TEXCOORD1;
};

output main(float3 position : POSITION, float2 texCoord : TEXCOORD0)
{
	output OUT;

	OUT.position = mul(glstate.matrix.mvp, float4(position.x/position.z, position.y/position.z, 1, 1));
	OUT.texCoord = float2(texCoord.x/position.z, texCoord.y/position.z);
	OUT.invW     = float2(1/position.z, 0);

	return OUT;
}